language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
before_install:
  - sudo apt-get -y install libicu-dev
  - npm install -g npm
script:
  - "npm test"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/070d1502bf5e5f56e80c
#  irc: "chat.freenode.net##node-irc"
